### ISSUE TITLE
StatefulSet not starting when watchNamespace is * and the MongoDb Resource is in another namespace

### ISSUE THREAD

**Issue by landorg** [mongodb/helm-charts#158]
This issue is copy paste of https://github.com/mongodb/helm-charts/issues/136. The PR https://github.com/mongodb/helm-charts/pull/152 mentioned was deployed in the version 0.7.4 of the helm chart but we still get the issue.

> The mongodb statefulset is created but isn't starting with the following error message:
> create Pod mongodb-0 in StatefulSet mongodb failed error: pods "mongodb-0" is forbidden: error looking up service account test/mongodb-database: serviceaccount "mongodb-database" not found

With PR #152 you can set **one** namespace where you'd want to deploy your dbs to. I'd want to deploy mongodbs to multiple namespaces and I don't want to change the helm chart options for that. 

imo the operator should be creating the sa & rbac along with the other db resources as the statefulset.
Thanks

related: https://github.com/mongodb/mongodb-kubernetes-operator/issues/1046

**Comment by kwill4026** [comment]
This worked for me for the enteprise operator chart. 
In the operator.yaml file is the env variable for WATCH_NAMESPACE
```
        - name: WATCH_NAMESPACE
{{- if .Values.operator.watchNamespace }}
          value: "{{ .Values.operator.watchNamespace }}"
```

Therefore in the values.yaml file, simply include **watchNamespace: '*'** under the operator.
it should look like:
```
operator:
  watchNamespace: '*'
```

Now when you install the chart, for instance in a namespace named Operator within a specific cluster, you should see it started up watching all namespaces in that specific cluster versus it watching only a single namespace. 
This allows me to install mongodb to several other namespaces.

If community version, just uncomment the watchNamespace in values.yaml

**Comment by mircea-cosbuc** [comment]
Hi @landorg,
As mentioned in https://github.com/mongodb/mongodb-kubernetes-operator/issues/1046#issuecomment-1195305177 , the chart only provides the option for creating a default database service account in the `database.namespace` value or in the chart's release namespace if the value is not provided. This is because we're trying to avoid giving too many permissions to the operator by default and the helm release should not manage database resources at the same time (e.g. upgrading your operator release should not accidentally make changes to your databases). Please use 
```
helm template --namespace=<your-db-namespace>  --show-only templates/database_roles.yaml mongodb/community-operator | kubectl apply -f -
```
to create the database roles in the additional namespaces you want to deploy your databases in.

**Comment by mircea-cosbuc** [comment]
Closing this as there was no follow-up on the discussion. Please feel free to open a different issue if encountering additional problems.
